name: aws delete SG not used

on:
  workflow_dispatch:

jobs:
  aws-cli-in-github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - run: |
          (comm -23  <(aws ec2 describe-security-groups --query 'SecurityGroups[*].GroupId'  --output text | tr '\t' '\n'| sort) <(aws ec2 describe-network-interfaces --output text --query NetworkInterfaces[].Groups[].GroupId | tr -d '\r' | tr "\t" "\n" | sort | uniq)) > No_used_security_groups.txt
