name: aws delete SG not used

on:
  workflow_dispatch:
    inputs:
      execute:
        description: Security Group remove execute [true or false]
        required: true

jobs:
  region1-aws-cli-in-github-actions-production:
    environment: production
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          python-version: '3.10'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ vars.REGION_ID_1 }}
      - name: Install dependencies pip & Awscli
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: List not used Security Groups
        run: |
          (comm -23  <(aws ec2 describe-security-groups --query 'SecurityGroups[*].GroupId'  --output text | tr '\t' '\n'| sort) <(aws ec2 describe-network-interfaces --output text --query NetworkInterfaces[].Groups[].GroupId | tr -d '\r' | tr "\t" "\n" | sort | uniq)) > No_used_security_groups_${{ vars.REGION_ID_1 }}.txt
          (comm -23  No_used_security_groups_${{ vars.REGION_ID_1 }}.txt <(aws ec2 describe-security-groups --filter  Name=group-name,Values=default --query 'SecurityGroups[*].[GroupId]' --output text | tr '\t' '\n'| sort)) > No_used_security_groups_without_default_${{ vars.REGION_ID_1 }}.txt
          cat No_used_security_groups_without_default_${{ vars.REGION_ID_1 }}.txt
      - name: Remove Security Groups not used
        if: github.event.inputs.execute == 'true'
        run: for id in `cat No_used_security_groups_without_default_${{ vars.REGION_ID_1 }}.txt` ; do echo $id ; aws ec2 delete-security-group --group-id $id; done
      - name: borrado del fallo
        if: ${{failure() }}
        run echo $id
      - name: Remove txt files
        run: |
          rm No_used_security_groups_${{ vars.REGION_ID_1 }}.txt
          rm No_used_security_groups_without_default_${{ vars.REGION_ID_1 }}.txt
          
  region2-aws-cli-in-github-actions-production2:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          python-version: '3.10'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ vars.REGION_ID_2 }}
      - name: Install dependencies pip & Awscli
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: List not used Security Groups
        run: |
          (comm -23  <(aws ec2 describe-security-groups --query 'SecurityGroups[*].GroupId'  --output text | tr '\t' '\n'| sort) <(aws ec2 describe-network-interfaces --output text --query NetworkInterfaces[].Groups[].GroupId | tr -d '\r' | tr "\t" "\n" | sort | uniq)) > No_used_security_groups${{ vars.REGION_ID_2 }}.txt
          (comm -23  No_used_security_groups${{ vars.REGION_ID_2 }}.txt <(aws ec2 describe-security-groups --filter  Name=group-name,Values=default --query 'SecurityGroups[*].[GroupId]' --output text | tr '\t' '\n'| sort)) > No_used_security_groups_without_default${{ vars.REGION_ID_2 }}.txt
          cat No_used_security_groups_without_default${{ vars.REGION_ID_2 }}.txt
      - name: Remove Security Groups not used
        if: github.event.inputs.execute == 'true'
        run: for id in `cat No_used_security_groups_without_default${{ vars.REGION_ID_2 }}.txt` ; do echo $id ; aws ec2 delete-security-group --group-id $id; done
      - name: Remove txt files
        run: |
          rm No_used_security_groups${{ vars.REGION_ID_2 }}.txt
          rm No_used_security_groups_without_default${{ vars.REGION_ID_2 }}.txt
