name: modify prefixlist

on:
  workflow_dispatch:
    inputs:
      id:
        description: id de lista a modificar [id]
        required: true
      description:
        description: descripcion de la lista [description]
        required: true
      cidr:
        description: CIDR [network 0.0.0.0/0]
        required: true

jobs:
  region1-aws-cli-in-github-actions-production:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          python-version: '3.10'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ vars.REGION_ID_1 }}
      - name: Install dependencies pip & Awscli
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Create Prefix-list
        run: 
          aws ec2 modify-managed-prefix-list --prefix-list-id ${{github.event.inputs.id} --add-entries Cidr=${{github.event.inputs.cidr}},Description="${{github.event.inputs.description}}"



                    
